# hongikjiki/utils/response_formatter.py
import logging
import re
from typing import List, Dict, Any, Set

logger = logging.getLogger("HongikJikiChatBot")

def format_response(results: List[Dict[str, Any]], message: str, llm_response: str) -> str:
    """
    Format the chatbot response with structured information
    
    Args:
        results: Search results from vector store
        message: Original user question
        llm_response: Response generated by the LLM
        
    Returns:
        Formatted response with quotes, tags, etc.
    """
    # Extract tags from results if available
    tags = set()
    quoted_insights = []
    source_info = []
    
    for i, result in enumerate(results):
        # Extract tags from metadata
        if 'metadata' in result and 'tags' in result['metadata']:
            result_tags = result['metadata']['tags']
            if isinstance(result_tags, list):
                tags.update(result_tags)
            elif isinstance(result_tags, str):
                tags.update([t.strip() for t in result_tags.split(',')])
        
        # Extract lecture info if available
        if 'metadata' in result:
            metadata = result['metadata']
            lecture_id = metadata.get('lecture_id', '')
            lecture_title = metadata.get('lecture_title', '')
            
            if lecture_id or lecture_title:
                info = f"[문서 {i+1}]"
                if lecture_title:
                    info += f" {lecture_title}"
                if lecture_id:
                    info += f" (강의 {lecture_id})"
                source_info.append(info)
        
        # Extract a quote if content exists
        content = result.get('content', '')
        if content:
            # Try to find a concise, meaningful sentence
            sentences = re.split(r'[.?!]', content)
            if len(sentences) > 1:
                # Use first non-empty sentence that's between 10-100 chars
                for sentence in sentences:
                    sentence = sentence.strip()
                    if 10 <= len(sentence) <= 100:
                        quoted_insights.append(f'"{sentence}"')
                        break
    
    # Format the response with the desired structure
    response = f"💬 {llm_response}\n\n"
    
    # Add sources if available
    if source_info:
        response += f"🔗 출처:\n" + "\n".join(source_info) + "\n\n"
    
    # Add quotes if available
    if quoted_insights:
        response += f"🔎 관련 인용:\n{quoted_insights[0]}\n\n"
    
    # Add tags if available
    if tags:
        tag_list = ' '.join([f"#{tag}" for tag in tags])
        response += f"🏷️ 관련 태그: {tag_list}"
    
    return response

def get_related_questions(tags: Set[str], current_question: str) -> List[str]:
    """
    Generate related questions based on tags
    
    Args:
        tags: Set of tags extracted from the user's question
        current_question: The current question to avoid duplicates
        
    Returns:
        List of related questions
    """
    # Create a set of canned questions for different tags
    tag_questions = {
        "감정": [
            "감정이 불안정한 이유는 무엇인가요?",
            "화가 날 때 어떻게 다스려야 할까요?",
            "자신의 감정을 이해하는 방법은 무엇인가요?"
        ],
        "관계": [
            "가족과의 갈등을 어떻게 해결할 수 있나요?",
            "인간관계에서 중요한 것은 무엇인가요?",
            "타인을 이해하는 방법은 무엇인가요?"
        ],
        "정신": [
            "마음과 정신의 차이는 무엇인가요?",
            "정신 수련을 어떻게 해야 하나요?",
            "정신이 흐트러질 때 집중하는 법은?"
        ],
        "수행": [
            "일상에서 어떻게 정법을 실천할 수 있나요?",
            "정법 수행은 무엇부터 시작해야 하나요?",
            "수행이 잘 되지 않을 때는 어떻게 해야 하나요?"
        ],
        "삶": [
            "참된 행복을 찾는 방법은 무엇인가요?",
            "인생의 목적을 어떻게 찾을 수 있을까요?",
            "의미 있는 삶을 사는 방법은 무엇인가요?"
        ]
        # Add more tag-based questions as needed
    }
    
    related = []
    for tag in tags:
        if tag in tag_questions:
            for question in tag_questions[tag]:
                if question.lower() != current_question.lower() and question not in related:
                    related.append(question)
    
    # Limit to 3 related questions
    return related[:3]